config:
  install_tree: $INSTALL_PATH/install
  source_cache: $INSTALL_PATH/.cache
  module_roots:
    tcl: $INSTALL_PATH/modules/tcl
  build_stage:
    - $tempdir
    - $INSTALL_PATH/.stage
  install_path_scheme: '${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH:6}'
  build_jobs: 36
