test:
  tags: [bb5_map]
  script:
    - |
      mail -s "test from gitlab" matwolf <<EOF
      Zis is a short test to see if we can notify you from a pipeline with the standard unix mail client.
      EOF
