stages:
  - setup
  - compilers
  - externals
  - applications
  - checks

default:
  tags: [bb5_map]  # Will use a special deployment user

.spack_job:
  variables:
    bb5_build_dir: pipeline
    # We will do this ourselves, will be on GPFS
    GIT_STRATEGY: none
    DEPLOYMENT_BRANCH: "transition-g2g"
    DEPLOYMENT_ROOT: "/gpfs/bbp.cscs.ch/ssd/apps/bsd"
    DEPLOYMENT_UPSTREAM: "/gpfs/bbp.cscs.ch/ssd/apps/bsd"
  rules:
    - if: '$CI_COMMIT_REF_NAME == "transition-g2g"'  # $CI_DEFAULT_BRANCH
      when: always
    - if: '$CI_EXTERNAL_PULL_REQUEST_IID'
      variables:
        DEPLOYMENT_BRANCH: "$CI_EXTERNAL_PULL_REQUEST_SOURCE_BRANCH_NAME"
        DEPLOYMENT_ROOT: "/gpfs/bbp.cscs.ch/ssd/apps/bsd/pulls/$CI_EXTERNAL_PULL_REQUEST_IID"
      when: always
    - when: never

clone_spack:
  extends: .spack_job
  stage: setup
  rules:
    - exists:
      - "$DEPLOYMENT_ROOT/spack"
      when: never
    - when: always
  script:
    - mkdir -p "$DEPLOYMENT_ROOT/spack"

update_spack:
  extends: .spack_job
  stage: setup
  rules:
    - exists:
      - "$DEPLOYMENT_ROOT/spack"
      when: always
    - when: never
  script:
    - rmdir "$DEPLOYMENT_ROOT/spack"
