stages:
  - setup
  - compilers
  - externals
  - applications
  - checks

.spack_job:
  variables:
    DEPLOYMENT_ROOT: "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins"
    DEPLOYMENT_UPSTREAM: "$DEPLOYMENT_ROOT"
  rules:
    - if: '$CI_EXTERNAL_PULL_REQUEST_IID'
      variables:
        DEPLOYMENT_ROOT: "/gpfs/bbp.cscs.ch/ssd/apps/hpc/jenkins/pulls/$CI_EXTERNAL_PULL_REQUEST_IID"
      when: always
    - if: '$CI_COMMIT_REF_NAME == "transition-g2g"'  # $CI_DEFAULT_BRANCH
      when: always
    - when: never
  tags: [bb5_map]

prepare_spack:
  extends: .spack_job
  stage: setup
  script:
    - env|grep DEPLOYMENT_
    - env
