config:
  install_tree:
    root: $SPACK_INSTALL_PREFIX/
    projections:
      all: install_{compiler.name}-{compiler.version}-{target}/{name}-{version}-{hash:6}
  source_cache: $SPACK_INSTALL_PREFIX/sources
  environments_root: $SPACK_INSTALL_PREFIX/environments
  # This seems to be the optimum for GPFS, according to @olupton
  build_jobs: 8