spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - py-amici  # BSD-276
          - py-atlalign
          - py-atlannot
          - py-atldld
          - py-atlinter
          - py-bba-datafetch
          - py-bba-webexporter
          - py-bglibpy
          - py-bluepyefe
          - py-bluepyemodel
          - py-bluepymm
          - py-bluepyopt
          - py-bluepyparallel
          - py-data-integrity-check
          - py-efel
          - py-nexusforge
          - py-nexus-sdk
          - py-token-fetch
          - py-visual-cortex-analysis
  packages:
    cuda:
      variants: +allow-unsupported-compilers
      # py-torch doesn't like cuda@12
      # this may still break: https://github.com/spack/spack/pull/25054#issuecomment-886531664
      # Using the script from that link, cuda@11.8 supports gcc@:11, cuda@12.0 supports gcc@:12
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    mvdtool:
      variants: ~mpi
    netcdf-c:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
    py-mvdtool:
      variants: ~mpi
    vtk:
      variants: ~mpi~ffmpeg~opengl2
    py-torch:
      variants: cuda_arch=70
  specs:
    - py-amici  # BSD-276
    - py-atlalign
    - py-atlannot
    - py-atldld
    - py-atlinter
    - py-bba-datafetch
    - py-bba-webexporter
    - py-bglibpy
    - py-bluepyefe
    - py-bluepyemodel
    - py-bluepymm
    - py-bluepyopt
    - py-bluepyparallel
    - py-data-integrity-check
    - py-efel
    - py-nexusforge
    - py-nexus-sdk
    - py-token-fetch
    - py-visual-cortex-analysis
