spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - brayns
        - brion+python
        - meshball
        - ultraliser
  specs:
    - brayns%gcc +brion ^ospray%intel@19.1.3.304 target=x86_64 ^intel-tbb%intel@19.1.3.304
    - brayns+net@1.1.0%gcc +brion ^brion@3.3.1 ^ospray%intel@19.1.3.304 target=x86_64 ^intel-tbb%intel@19.1.3.304
    - brion +python
    - meshball ^brion@3.1.0
    - ultraliser ^hdf5~mpi
