spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - py-bba-datafetch
        - py-bba-webexporter
        - py-data-integrity-check
        - py-nexusforge
        - py-nexus-sdk
        - py-token-fetch
  packages:
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    mvdtool:
      variants: ~mpi
    netcdf-c:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
    py-mvdtool:
      variants: ~mpi
    vtk:
      variants: ~mpi~ffmpeg~opengl2
  specs:
    - py-bba-datafetch
    - py-bba-webexporter
    - py-data-integrity-check
    - py-nexusforge
    - py-nexus-sdk
    - py-token-fetch
