spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - brayns
        - py-brayns
        - brion+python
        - meshball
        - ultraliser
  specs:
    - brayns%gcc ^ospray%intel ^intel-tbb%intel
    - py-brayns
    - brion +python
    - ultraliser ^hdf5~mpi
