spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - asciitoh5
          - model-neocortex
          - nest
          - neurodamus-core
          - neurodamus-hippocampus
          - neurodamus-neocortex
          - neurodamus-thalamus
          - neurodamus-mousify
          - parquet-converters
          - py-basalt
          - py-mvdtool
          - py-neurodamus+all_deps
          - py-pytouchreader
          - reportinglib
          - spatial-index
          - spykfunc
          - steps
          - synapsetool
          - touchdetector
          - unit-test-translator
        projections:
          all: '{name}/{version}'
          ^neuron+knl: '{name}-knl/{version}'
          +common: '{name}/{version}-commonmods'
          +plasticity: '{name}-plasticity/{version}'
          +ngv+metabolism: '{name}-multiscale/{version}'
  packages:
    steps:
      variants: +petsc
    trilinos:
      version: [13.0.1]
  specs:
    - neuron+tests+coreneuron
    - neuron+tests+nmodl+sympy+coreneuron
    # Try +rx3d after https://github.com/neuronsimulator/nrn/pull/2235?
    - neuron%nvhpc+caliper+coreneuron+gpu~rx3d+tests+openmp
    - neuron%nvhpc+caliper+coreneuron+gpu~rx3d+tests~openmp+nmodl
    - neuron%nvhpc+caliper+coreneuron+gpu~rx3d+tests+openmp+nmodl+sympy
    - nest@2.20.1
    - neurodamus-core~common~~coreneuron
    - neurodamus-core+common~~coreneuron
    - neurodamus-hippocampus+coreneuron+caliper
    - neurodamus-mousify+coreneuron+caliper
    - neurodamus-neocortex~plasticity+coreneuron+caliper
    - neurodamus-neocortex+plasticity+coreneuron+caliper
    - neurodamus-neocortex+ngv+metabolism+caliper~~coreneuron
    - neurodamus-thalamus+coreneuron+caliper
    - neuron+coreneuron build_type=Debug
    - neuron+coreneuron build_type=FastDebug
    - nmodl
    - parquet-converters
    - py-neurodamus+all_deps
    - py-pytouchreader
    - reportinglib
    - spatial-index
    - spykfunc
    - steps
    - synapsetool
    - touchdetector
    - unit-test-translator
