spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - py-amici  # BSD-276
          - py-atlalign
          - py-atlannot
          - py-atldld
          - py-atlinter
          - py-bba-datafetch
          - py-bba-webexporter
          - py-bglibpy
          - py-bluepyefe
          - py-bluepyemodel
          - py-bluepymm
          - py-bluepyopt
          - py-bluepyparallel
          - py-data-integrity-check
          - py-efel
          - py-nexusforge
          - py-nexus-sdk
          - py-token-fetch
          - py-visual-cortex-analysis
  packages:
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    mvdtool:
      variants: ~mpi
    netcdf-c:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
    py-mvdtool:
      variants: ~mpi
    vtk:
      variants: ~mpi~ffmpeg~opengl2
  specs:
    - py-amici  # BSD-276
    - py-atlalign
    - py-atlannot
    - py-atldld
    - py-atlinter
    - py-bba-datafetch
    - py-bba-webexporter
    - py-bglibpy
    - py-bluepyefe
    - py-bluepyemodel
    - py-bluepymm
    - py-bluepyopt
    - py-bluepyparallel
    - py-data-integrity-check
    - py-efel
    - py-nexusforge
    - py-nexus-sdk
    - py-token-fetch
    - py-visual-cortex-analysis
