spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - boost
          - caliper
          - gmsh
          - hdf5+mpi
          - highfive+mpi
          - neuron+mpi
          - omega-h
          - petsc
          - py-cgal-pybind
          - py-dask-mpi
          - py-flake8
          - py-h5py+mpi
          - py-libsonata
          - py-mpi4py
          - py-notebook
          - py-numpy
          - py-pip
          - py-poisson-recon-pybind
          - py-pytest
          - py-rtree
          - py-scikit-learn
          - py-scipy
          - py-virtualenv
          - python-dev
        projections:
          all: '{name}/{version}'
          petsc+complex+int64+mpi: '{name}-complex/{version}'
          ^petsc+complex: '{name}-complex/{version}'
  packages:
    petsc:
      variants: ~hypre
  specs:
    - boost+atomic+chrono+date_time+filesystem+json+locale+log+math+program_options+python+random+regex+serialization+shared+signals+stacktrace+system+test+timer+type_erasure
    - caliper+cuda cuda_arch=70
    - gmsh+metis+mpi+openmp+shared
    - hdf5+mpi
    - highfive+mpi
    - metis+int64
    - neuron+mpi
    - omega-h+gmsh
    - petsc+int64+mpi
    - petsc+complex+int64+mpi
    - py-cgal-pybind
    - py-dask-mpi
    - py-flake8
    - py-h5py
    - py-libsonata
    - py-mpi4py
    - py-notebook
    - py-numpy
    - py-pip
    - py-poisson-recon-pybind
    - py-rtree
    - py-scikit-learn
    - py-scipy
    - py-pytest  # requested by Pramod
    - py-virtualenv
    - python-dev
    - sundials+int64
    - superlu-dist@5.4.0
