spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - boost
          - caliper
          - gmsh
          - hdf5
          - highfive+mpi
          - libsonata-report
          - neuron+mpi
          - omega-h
          - petsc
          - slepc
          - py-cgal-pybind
          - py-dask-mpi
          - py-flake8
          - py-h5py+mpi
          - py-libsonata
          - py-libsonata-mpi
          - py-mpi4py
          - py-notebook
          - py-numpy
          - py-petsc4py
          - py-pytest
          - py-slepc4py
          - py-pip
          - py-poisson-recon-pybind
          - py-rtree
          - py-scikit-learn
          - py-scipy
          - py-virtualenv
          - python-dev
          - snakemake
        projections:
          all: '{name}/{version}'
  specs:
    - boost+atomic+chrono+date_time+filesystem+json+locale+log+math+program_options+python+random+regex+serialization+shared+signals+stacktrace+system+test+timer+type_erasure
    - caliper+vtune+cuda cuda_arch=70
    - gmsh
    - hdf5+cxx+hl+mpi
    - highfive+mpi
    - libsonata-report
    - metis+int64
    - neuron+mpi
    - omega-h+gmsh
    - petsc+int64+mpi
    - slepc~arpack ^petsc+int64+mpi
    - py-cgal-pybind
    - py-dask-mpi
    - py-flake8
    - py-h5py
    - py-libsonata
    - py-libsonata-mpi
    - py-mpi4py
    - py-notebook
    - py-numpy
    - py-petsc4py ^petsc+int64+mpi
    - py-slepc4py ^slepc~arpack ^petsc+int64+mpi
    - py-pytest  # BSD-433
    - py-pip
    - py-poisson-recon-pybind
    - py-rtree
    - py-scikit-learn
    - py-scipy
    - py-virtualenv
    - python-dev
    - snakemake
    - sundials+int64
    - superlu-dist@5.4.0
