spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - asciitoh5
          - model-neocortex
          - nest
          - neurodamus-core
          - neurodamus-hippocampus
          - neurodamus-neocortex
          - neurodamus-thalamus
          - neurodamus-mousify
          - parquet-converters
          - py-basalt
          - py-mvdtool
          - 'py-neurodamus+all_deps'
          - py-pytouchreader
          - reportinglib
          - spatial-index
          - spykfunc
          - steps
          - synapsetool
          - touchdetector
          - unit-test-translator
        projections:
          all: '{name}/{version}'
          ^coreneuron+knl: '{name}-knl/{version}'
          +common: '{name}/{version}-commonmods'
          +plasticity: '{name}-plasticity/{version}'
          +ngv+metabolism: '{name}-multiscale/{version}'
  specs:
   #- coreneuron+tests
   #- coreneuron+tests+nmodl+sympy
   #- coreneuron%nvhpc+tests+gpu+openmp
   #- coreneuron%nvhpc+tests+gpu+openmp+nmodl+sympy
    - model-neocortex
    - nest@2.20.1
    - neurodamus-core~common
    - neurodamus-core+common
    - neurodamus-hippocampus+coreneuron+caliper
    - neurodamus-hippocampus+coreneuron+caliper^coreneuron+knl
    - neurodamus-mousify+coreneuron+caliper
    - neurodamus-neocortex+coreneuron+caliper
    - neurodamus-neocortex+coreneuron+caliper^coreneuron+knl
    - neurodamus-neocortex+plasticity+coreneuron+caliper
    - neurodamus-neocortex+ngv+metabolism+caliper
    - neurodamus-thalamus+coreneuron+caliper
    - neurodamus-thalamus+coreneuron+caliper^coreneuron+knl
    - neuron+coreneuron+tests
   #- neuron+coreneuron+tests ^coreneuron+gpu~shared
    - neuron+debug
    - nmodl
    - parquet-converters
    - py-neurodamus+all_deps
    - py-pytouchreader
    - reportinglib
    - spatial-index
    - spykfunc
    - steps+petsc
    - synapsetool
    - touchdetector
    - unit-test-translator
