spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - brainbuilder
          - circuit-analysis
          - circuit-build
          - connectome-tools
          - emsim
          - placement-algorithm
          - psp-validation
          - py-archngv
          - py-atlas-building-tools
          - py-bbp-analysis-framework
          - py-bbp-workflow
          - py-bbp-workflow-cli
          - py-bluepy
          - py-bluepysnap
          - py-connectome-manipulator
          - py-entity-management
          - py-morphio
          - py-morph-tool
          - py-neuror
          - py-region-grower
          - py-cwl-registry
  packages:
    libsonata:
      variants: ~mpi
    mvdtool:
      variants: ~mpi
    netcdf-c:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
    py-mvdtool:
      variants: ~mpi
    vtk:
      variants: ~mpi~ffmpeg~opengl2
  specs:
    - brainbuilder
    - circuit-build
    - connectome-tools
    - emsim
    - placement-algorithm
    - psp-validation
    - py-archngv
    - py-atlas-building-tools
    - py-bbp-analysis-framework
    - py-bbp-workflow
    - py-bbp-workflow-cli
    - py-bluepy
    - py-bluepysnap
    - py-entity-management
    - py-morphio
    - py-neuror
    - py-morph-tool+neuron
    - py-region-grower
    - py-cwl-registry
