spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - brayns
          - brion+python
          - meshball
          - ultraliser
  packages:
    ospray:
      version: [19.1.3.304]
    intel-tbb:
      version: [19.1.3.304]
  specs:
    - brayns +brion
    - brayns@1.1.0 +brion+net ^brion@3.3.1
    - brion +python
    - ultraliser ^hdf5~mpi
