spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - asciitoh5
          - model-neocortex
          - nest
          - neurodamus-hippocampus
          - neurodamus-neocortex
          - neurodamus-thalamus
          - neurodamus-mousify
          - parquet-converters
          - py-basalt
          - py-mvdtool
          - py-neurodamus
          - py-pytouchreader
          - reportinglib
          - spatial-index
          - spykfunc
          - steps
          - synapsetool
          - touchdetector
          - unit-test-translator
        projections:
          all: '{name}/{version}'
          ^neuron+knl: '{name}-knl/{version}'
          +common: '{name}/{version}-commonmods'
          +plasticity: '{name}-plasticity/{version}'
          +ngv+metabolism: '{name}-multiscale/{version}'
          ^petsc+complex: '{name}-complex/{version}'
  specs:
    - neuron+tests+coreneuron
    - neuron+tests+nmodl+sympy+coreneuron
    - neuron%nvhpc+caliper+coreneuron+gpu+tests+openmp
    - neuron%nvhpc+caliper+coreneuron+gpu+tests~openmp+nmodl
    - neuron%nvhpc+caliper+coreneuron+gpu+tests+openmp+nmodl+sympy
    - nest@2.20.1
    - neurodamus-hippocampus+coreneuron+caliper
    - neurodamus-mousify+coreneuron+caliper
    - neurodamus-neocortex~plasticity+coreneuron+caliper
    - neurodamus-neocortex+plasticity+coreneuron+caliper
    - neurodamus-neocortex+ngv+metabolism+caliper~~coreneuron
    - neurodamus-thalamus+coreneuron+caliper
    - neuron+coreneuron build_type=Debug
    - neuron+coreneuron build_type=FastDebug
    - nmodl
    - parquet-converters
    - py-neurodamus
    - py-pytouchreader
    - reportinglib
    - spatial-index
    - spykfunc
    - steps
  # - steps@5
  # - steps@5 ^petsc+complex
    - synapsetool
    - touchdetector
    - unit-test-translator
