spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - brainbuilder
          - circuit-analysis
          - circuit-build
          - connectome-tools
          - emsim
          - gene-expression-volume
          - placement-algorithm
          - psp-validation
          - py-archngv
          - py-atlas-building-tools
          - py-bbp-analysis-framework
          - py-bbp-workflow
          - py-bbp-workflow-cli
          - py-bluepy
          - py-bluepysnap
          - py-currentscape
          - py-entity-management
          - py-minis-validation
          - py-morphio
          - py-morph-tool
          - py-morphology-repair-workflow
          - py-region-grower
          - py-sonata-network-reduction
          - regiodesics
  packages:
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    mvdtool:
      variants: ~mpi
    netcdf-c:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
    py-mvdtool:
      variants: ~mpi
    vtk:
      variants: ~mpi~ffmpeg~opengl2
  specs:
    - brainbuilder
    - circuit-build
    - connectome-tools
    - emsim
    - gene-expression-volume
    - placement-algorithm
    - psp-validation
    - py-archngv
   #- py-atlas-building-tools
    - py-bbp-analysis-framework
    - py-bbp-workflow
    - py-bbp-workflow-cli
    - py-bluepy
    - py-bluepysnap
    - py-currentscape
    - py-entity-management
    - py-minis-validation
    - py-morphio
    - py-morphology-repair-workflow
    - py-morph-tool
    - py-region-grower
    - py-sonata-network-reduction
    - regiodesics
