spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - boost
        - caliper
        - gmsh
        - hdf5+mpi%gcc@11.2.0
        - highfive+mpi%gcc@11.2.0
        - neuron+mpi~debug%intel
        - omega-h
        - petsc+int64+mpi
        - py-cgal-pybind
        - py-dask-mpi
        - py-flake8
        - py-h5py+mpi
        - py-libsonata
        - py-mpi4py
        - py-notebook
        - py-numpy
        - py-poisson-recon-pybind
        - py-rtree
        - py-scikit-learn
        - py-scipy
        - py-tensorflow
        - python-dev
        - py-virtualenv
      projections:
        all: '{name}/{version}'
        'omega-h+gmsh': '{name}/{version}-gmsh'

  definitions:
    - compilers: ['%gcc@11.2.0', '%gcc@9.4.0', '%clang']
  specs:
    - boost+python
    - caliper+cuda cuda_arch=70
    - gmsh+metis+mpi+oce+openmp+shared
    - hdf5+mpi
    - matrix:
      - [highfive+mpi]
      - [$compilers]
    - hypre+int64+mpi
    - matrix:
      - [libsonata+mpi]
      - [$compilers]
    - metis+int64
    - matrix:
      - [morphio+mpi]
      - [$compilers]
    - neuron+mpi~debug%intel
    - omega-h+trilinos
    - omega-h+gmsh+trilinos
    - petsc~int64+mpi
    - petsc+int64+mpi
    - py-breathe
    - py-cgal-pybind
    - py-clustershell
    - py-cmake-format
    - py-coverage
    - py-dask-mpi
    - py-docopt
    - py-exhale
    - py-flake8
    - py-h5py
    - py-libsonata
    - py-matplotlib
    - py-mpi4py
    - py-notebook
    - py-numpy
    - py-pip
    - py-poisson-recon-pybind
    - py-rtree
    - py-scikit-learn
    - py-scipy
    - py-tensorflow
    - py-virtualenv
    - python-dev
    - sundials+int64
    - superlu-dist@5.4.0
