spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - brayns
          - brion+python
          - meshball
          - ultraliser
  specs:
    - brayns%gcc +brion ^ospray%intel@19.1.3.304 target=x86_64 ^intel-tbb%intel@19.1.3.304
    - brayns@1.1.0%gcc +brion+net ^brion@3.3.1 ^ospray%intel@19.1.3.304 target=x86_64 ^intel-tbb%intel@19.1.3.304
    - brion +python
    - ultraliser ^hdf5~mpi
