spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - nest
          - neurodamus-models
          - parquet-converters
          - py-archive-advisor
          - py-basalt
          - py-brain-indexer
          - py-functionalizer
          - py-mvdtool
          - py-neurodamus
          - py-pytouchreader
          - steps
          - touchdetector
          - unit-test-translator
        projections:
          all: '{name}/{version}'
          neurodamus-models model=hippocampus: 'neurodamus-hippocampus/{version}'
          neurodamus-models model=neocortex +plasticity: 'neurodamus-neocortex-plasticity/{version}'
          neurodamus-models model=neocortex +ngv+metabolism: 'neurodamus-neocortex-multiscale/{version}'
          neurodamus-models model=neocortex: 'neurodamus-neocortex/{version}'
          neurodamus-models model=thalamus: 'neurodamus-thalamus/{version}'
  specs:
    - neuron+tests+coreneuron
    - neuron+tests+coreneuron+sympy
    - neuron%nvhpc+caliper+coreneuron+gpu+tests+openmp
    - neuron%nvhpc+caliper+coreneuron+gpu+tests~openmp
    - neuron%nvhpc+caliper+coreneuron+gpu+tests+openmp+sympy
    - nest@2.20.1
    - neurodamus-models model=hippocampus +coreneuron+caliper
    - neurodamus-models model=neocortex ~plasticity+coreneuron+caliper
    - neurodamus-models model=neocortex +plasticity+coreneuron+caliper
    - neurodamus-models model=neocortex +ngv+metabolism+caliper~~coreneuron
    - neurodamus-models model=thalamus +coreneuron+caliper
    - neuron+coreneuron build_type=Debug
    - neuron+coreneuron build_type=FastDebug
    - nmodl
    - parquet-converters
    - py-archive-advisor
    - py-brain-indexer
    - py-functionalizer
    - py-neurodamus
    - py-pytouchreader
    - steps
    - touchdetector
    - unit-test-translator
