spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - boost
          - caliper
          - gmsh
          - hdf5+mpi
          - highfive+mpi
          - neuron+mpi~debug
          - omega-h
          - petsc+int64+mpi
          - py-cgal-pybind
          - py-dask-mpi
          - py-flake8
          - py-h5py+mpi
          - py-libsonata
          - py-mpi4py
          - py-notebook
          - py-numpy
          - py-poisson-recon-pybind
          - py-rtree
          - py-scikit-learn
          - py-scipy
          - py-virtualenv
          - python-dev
        projections:
          all: '{name}/{version}'
          'omega-h+gmsh': '{name}/{version}-gmsh'
  specs:
    - boost+python
    - caliper+cuda cuda_arch=70
    - gmsh+metis+mpi+oce+openmp+shared
    - hdf5+mpi
    - highfive+mpi
    - hypre+int64+mpi
    - metis+int64
    - neuron+mpi
    - omega-h+gmsh
    - petsc~int64+mpi
    - petsc+int64+mpi
    - py-cgal-pybind
    - py-dask-mpi
    - py-flake8
    - py-h5py
    - py-libsonata
    - py-mpi4py
    - py-notebook
    - py-numpy
    - py-poisson-recon-pybind
    - py-rtree
    - py-scikit-learn
    - py-scipy
    - py-virtualenv
    - python-dev
    - sundials+int64
    - superlu-dist@5.4.0
