spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - asciitoh5
        - model-neocortex
        - nest
        - neurodamus-core
        - neurodamus-hippocampus
        - neurodamus-neocortex
        - neurodamus-thalamus
        - neurodamus-mousify
        - parquet-converters
        - py-basalt
        - 'py-mvdtool%gcc'
        - 'py-neurodamus+all_deps'
        - py-pytouchreader
        - reportinglib
        - spatial-index
        - spykfunc
        - steps
        - 'synapsetool%gcc'
        - touchdetector
        - unit-test-translator
      projections:
        all: '{name}/{version}'
        ^coreneuron+knl: '{name}-knl/{version}'
        +common: '{name}/{version}-commonmods'
        +plasticity: '{name}-plasticity/{version}'
  specs:
    - asciitoh5@1.0
    - coreneuron%intel+tests
    - coreneuron%nvhpc+tests+gpu+openmp
    - model-neocortex%intel ^neuron%intel
    - nest@2.20.1
    - neurodamus-core~common%intel ^neuron%intel
    - neurodamus-core+common
    - neurodamus-hippocampus+coreneuron%intel ^coreneuron%intel+caliper ^neuron%intel
    - neurodamus-hippocampus+coreneuron%intel ^coreneuron%intel+caliper+knl ^neuron%intel
    - neurodamus-mousify+coreneuron%intel^coreneuron%intel+caliper ^neuron%intel
    - neurodamus-neocortex+coreneuron%intel^coreneuron%intel+caliper ^neuron%intel
    - neurodamus-neocortex+coreneuron%intel^coreneuron%intel+caliper+knl ^neuron%intel
    - neurodamus-neocortex+coreneuron+plasticity%intel^coreneuron%intel+caliper ^neuron%intel
    - neurodamus-thalamus+coreneuron%intel^coreneuron%intel+caliper ^neuron%intel
    - neurodamus-thalamus+coreneuron%intel^coreneuron%intel+caliper+knl ^neuron%intel
    - neuron%intel+coreneuron+tests ^coreneuron%intel
    - neuron%nvhpc+coreneuron+tests ^coreneuron+gpu%nvhpc
    - nmodl
    - parquet-converters
    - py-basalt@0.2.9
    - py-neurodamus+all_deps
    - py-pytouchreader
    - reportinglib%intel
    - spatial-index
    - spykfunc
    - steps+petsc
    - synapsetool
    - touchdetector
    - unit-test-translator
