spack:
  view: false
  modules:
    default:
      tcl:
        include:
          - asciitoh5
          - model-neocortex
          - morpho-kit
          - nest
          - neurodamus-models
          - neurodamus-mousify
          - parquet-converters
          - py-archive-advisor
          - py-basalt
          - py-mvdtool
          - py-neurodamus
          - py-pytouchreader
          - spatial-index
          - spykfunc
          - steps
          - synapsetool
          - touchdetector
          - unit-test-translator
        projections:
          all: '{name}/{version}'
          ^neuron+knl: '{name}-knl/{version}'
          +common: '{name}/{version}-commonmods'
          +plasticity: '{name}-plasticity/{version}'
          +ngv+metabolism: '{name}-multiscale/{version}'
  specs:
    - morpho-kit
    - neuron+tests+coreneuron
    - neuron+tests+coreneuron+sympy
    - neuron%nvhpc+caliper+coreneuron+gpu+tests+openmp
    - neuron%nvhpc+caliper+coreneuron+gpu+tests~openmp
    - neuron%nvhpc+caliper+coreneuron+gpu+tests+openmp+sympy
    - nest@2.20.1
    - neurodamus-mousify+coreneuron+caliper
    - neurodamus-models model=hippocampus +coreneuron+caliper
    - neurodamus-models model=neocortex ~plasticity+coreneuron+caliper
    - neurodamus-models model=neocortex +plasticity+coreneuron+caliper
    - neurodamus-models model=neocortex +ngv+metabolism+caliper~~coreneuron
    - neurodamus-models model=thalamus +coreneuron+caliper
    - neuron+coreneuron build_type=Debug
    - neuron+coreneuron build_type=FastDebug
    - nmodl
    - parquet-converters
    - py-archive-advisor
    - py-neurodamus
    - py-pytouchreader
    - spatial-index
    - spykfunc
    - steps
    - steps@5
    - synapsetool
    - touchdetector
    - unit-test-translator
