modules:

  enable::
    - tcl
    - lmod

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    hash_length: 0
    whitelist:
      - allinea-forge
      - cuda
      - functionalizer
      - gcc
      - hpctoolkit
      - 'hpe-mpi%gcc'
      - ior
      - imb
      - intel
      - intel-mpi
      - intel-parallel-studio
      - likwid
      - llvm
      - mvapich2
      - 'neurodamus%intel'
      - 'neuron+mpi%intel'
      - openmpi
      - osu-micro-benchmarks
      - parquet-converters
      - pgi
      - 'python%gcc'
      - qt
      - spark
      - spykfunc
      - steps
      - stat
      - touchdetector
    blacklist:
      - '%gcc'
      - '%intel'
      - '%llvm'
      - '%pgi'
    naming_scheme: '${PACKAGE}/${VERSION}'
    gcc:
      environment:
        set:
          MPICC_CC: 'gcc'
          MPICXX_CXX: 'g++'
          MPIF90_F90: 'gfortran'
    intel-parallel-studio:
      environment:
        set:
          MPICC_CC: 'icc'
          MPICXX_CXX: 'icpc'
          MPIF90_F90: 'ifort'
    intel:
      environment:
        set:
          MPICC_CC: 'icc'
          MPICXX_CXX: 'icpc'
          MPIF90_F90: 'ifort'
    pgi:
      environment:
        set:
          MPICC_CC: 'pgcc'
          MPICXX_CXX: 'pgc++'
          MPIF90_F90: 'pgfortran'
    llvm:
      environment:
        set:
          MPICC_CC: 'clang'
          MPICXX_CXX: 'clang++'
          MPIF90_F90: 'gfortran'
    intel-mpi:
      environment:
        set:
          I_MPI_ROOT: '${PREFIX}'
          I_MPI_EXTRA_FILESYSTEM: '1'
          I_MPI_EXTRA_FILESYSTEM_LIST: gpfs
    likwid@:4.3.1:
      environment:
        set:
          KMP_INIT_AT_FORK: 'FALSE'
    all:
      suffixes:
        '+knl': knl
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
