packages:
  autoconf:
    version: [2.69]
    externals:
    - spec: autoconf@2.69
      prefix: /usr
  automake:
    version: [1.13.4]
    externals:
    - spec: automake@1.13.4
      prefix: /usr
  boost:
    variants: +pic
  cmake:
    version: [3.15.7]
  curl:
    version: [7.29.0]
    externals:
    - spec: curl@7.29.0
      prefix: /usr
  darshan-runtime:
    variants: +slurm
  eigen:
    variants: ~fftw~gmp~metis~mpfr~scotch
  hadoop:
    version: [2.10.1]
  hdf5:
    variants: +cxx+hl
  icu4c:
    version: [64.1]
  intel-mkl:
    version: [2018.3.222]
    # Drags in heavy PEARL dependencies
  intltool:
    version: [0.50.2]
    externals:
    - spec: intltool@0.50.2
      prefix: /usr
  julia:
    variants: +external_llvm
  libtool:
    version: [2.4.2]
    externals:
    - spec: libtool@2.4.2
      prefix: /usr
  llvm:
    variants: +link_dylib
  m4:
    version: [1.4.16]
    externals:
    - spec: m4@1.4.16
      prefix: /usr
  node-js:
    version: [14.13.0]
  omega-h:
    variants: +trilinos
  opencv:
    variants: ~gtk~vtk
  openssl:
    version: [1.0.2k]
    externals:
    - spec: openssl@1.0.2k
      prefix: /usr
  opengl:
    buildable: false
    version: [4.5]
    externals:
    - spec: opengl@4.5
      prefix: /usr
  perl:
    version: [5.16.3]
    externals:
    - spec: perl@5.16.3
      prefix: /usr
  petsc:
    variants: ~fortran
  python:
    variants: +tk
    version: [3.8.3]
  qt:
    variants: ~ssl~sql~tools
  range-v3:
    variants: ~doc
  slurm:
    buildable: false
    version: [17.02]
    externals:
    - spec: slurm@17.02
      prefix: /usr
  steps:
    variants: +lapack+petsc+mpi
  superlu-dist:
    variants: +int64
  tar:
    version: [1.28]
    externals:
    - spec: tar@1.28
      prefix: /usr
  timemory:
    variants: +mpi~cuda+cupti+caliper~gperftools~python@3.0.0a
  trilinos:
    variants: +kokkos+teuchos+openmp~amesos~hypre~superlu-dist~mumps~metis~suite-sparse
    version: [xsdk-0.4.0-rc1]
  all:
    compiler: [gcc@9.3.0, intel@19.1.2.254, gcc@4.8.5]
    target: [x86_64]
    providers:
      mpi: [hpe-mpi]
      scalapack: [intel-mkl, netlib-scalapack]
      lapack: [intel-mkl, openblas]
      blas: [intel-mkl, openblas]
