def deployment_directory(parent) {
    def pull = env.ghprbPullId
    if (parent || pull == null) {
        return "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment"
    } else {
        return "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment/pulls/${pull}"
    }
}

def post_process(stage, redeploy, reconfigure) {
    dir("${BASEDIR}") {
        if (redeploy) {
            sh "./deploy.sh -l ${stage}"
        }

        if (reconfigure) {
            sh "./deploy.sh -c ${stage}"
        }
    }
}

pipeline {
    agent {
        label 'bb5-full'
    }

    options {
        timestamps()
    }

    parameters {
        string(name: 'DEPLOYMENT_DATE',
               defaultValue: 'latest',
               description: 'Date to use when deploying, in YYYY-MM-DD format, or "latest".')
        booleanParam(name: 'REDEPLOY',
                     defaultValue: false,
                     description: 'Set the "latest" symlink to the currently built deployment')
        booleanParam(name: 'UPDATE_CONFIGURATION',
                     defaultValue: true,
                     description: 'Update the user-facing configuration files')
        booleanParam(name: 'BUILDCACHE',
                     defaultValue: true,
                     description: 'Use cache to install already compiled software')
        booleanParam(name: 'SOURCECACHE',
                     defaultValue: true,
                     description: 'Use cache to install already downloaded sources')
        text(name: 'STAGES',
             defaultValue: 'compilers\ntools\nserial-libraries\npython-packages\nparallel-libraries\napplications',
             description: 'Which parts of the deployment chain to build')
    }

    environment {
        DEPLOYMENT_UPSTREAM = deployment_directory(true)
        DEPLOYMENT_ROOT = deployment_directory(false)
        BASEDIR = "${DEPLOYMENT_ROOT}/deploy/spack/deploy"
        TMPDIR = "/dev/shm/jenkins"
    }

    stages {
        stage('Setup') {
            // General setup: make sure that Spack is installed and that
            // license files are available to Spack
            steps {
                sh "env"
                sh "false"
                dir("${DEPLOYMENT_ROOT}/deploy/spack") {
                    git(url: "https://github.com/BlueBrain/spack.git", branch: "spack_chain")
                }
                dir("${DEPLOYMENT_ROOT}/deploy/spack/etc/spack/licenses") {
                    git(url: "ssh://bbpcode.epfl.ch/user/kumbhar/spack-licenses")
                }
            }
        }

        // stage('Archival') {
        //     // When tagging a new release, reset the symlinks pointing to
        //     // the last release
        //     when {
        //         tag pattern: "release-\\d+", comparator: "REGEXP"
        //     }

        //     steps {
        //         sh "ls"
        //     }
        // }

        stage('Compilers') {
            when {
                expression {
                    return 'compilers' in params.STAGES.tokenize()
                }
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh compilers"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/compilers.xml"
                    junit testResults: "stacks/compilers.xml", allowEmptyResults: true
                }

                success {
                    post_process("compilers", params.REDEPLOY, false)
                }
            }
        }

        stage('Tools') {
            when {
                expression {
                    return 'tools' in params.STAGES.tokenize()
                }
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh tools"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/tools.xml"
                    junit testResults: "stacks/tools.xml", allowEmptyResults: true
                }

                success {
                    post_process("tools", params.REDEPLOY, false)
                }
            }
        }

        stage('Serial Libraries') {
            when {
                expression {
                    return 'serial-libraries' in params.STAGES.tokenize()
                }
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh serial-libraries"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/serial-libraries.xml"
                    junit testResults: "stacks/serial-libraries.xml", allowEmptyResults: true
                }

                success {
                    post_process("serial-libraries", params.REDEPLOY, false)
                }
            }
        }

        stage('Python Packages') {
            when {
                expression {
                    return 'python-packages' in params.STAGES.tokenize()
                }
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh python-packages"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/python-packages.xml"
                    junit testResults: "stacks/python-packages.xml", allowEmptyResults: true
                }

                success {
                    post_process("python-packages", params.REDEPLOY, false)
                }
            }
        }

        stage('Parallel Libraries') {
            when {
                expression {
                    return 'parallel-libraries' in params.STAGES.tokenize()
                }
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh parallel-libraries"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/parallel-libraries.xml"
                    junit testResults: "stacks/parallel-libraries.xml", allowEmptyResults: true
                }

                success {
                    post_process("parallel-libraries", params.REDEPLOY, false)
                }
            }
        }

        stage('Applications') {
            when {
                expression {
                    return 'applications' in params.STAGES.tokenize()
                }
            }

            steps {
                withEnv(['SOURCECACHE=false',
                         'BUILDCACHE=false']) {
                    dir("${BASEDIR}") {
                        sh "./deploy.sh applications"
                    }
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/applications.xml"
                    junit testResults: "stacks/applications.xml", allowEmptyResults: true
                }

                success {
                    post_process("applications", params.REDEPLOY, params.UPDATE_CONFIGURATION)
                }
            }
        }
    }
}
