spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - brayns
        - brion+python
        - meshball
        - ultraliser
  specs:
    - brayns%gcc +brion ^brion@3.3.5 ^ospray%intel
    - brayns@1.1.0%gcc +brion ^brion@3.3.1 ^ospray%intel
    - brion@3.1.0 +python
    - brion@3.2.0 +python
    - brion@3.3.0 +python
    - brion@3.3.1 +python
    - meshball ^brion@3.1.0
    - ultraliser ^hdf5~mpi
