spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - brayns
        - brion+python
        - meshball
        - ultraliser
  specs:
    - brayns%gcc +brion ^ospray%intel target=x86_64 ^intel-tbb%intel
    - brayns@1.0.1%gcc +brion ^brion@3.1.0 ^ospray%intel target=x86_64 ^intel-tbb%intel
    - brion +python
    - meshball ^brion@3.1.0
    - ultraliser ^hdf5~mpi
