spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - brainbuilder
        - circuit-build
        - placement-algorithm
        - py-region-grower
  packages:
    hdf5:
      variants: ~mpi+hl
    highfive:
      variants: ~mpi
    libsonata:
      variants: ~mpi
    mvdtool:
      variants: ~mpi
    netcdf-c:
      variants: ~mpi
    py-h5py:
      variants: ~mpi
    py-mvdtool:
      variants: ~mpi
    vtk:
      variants: ~mpi~ffmpeg~opengl2
  specs:
    - brainbuilder
    - circuit-build
    - placement-algorithm
    - py-region-grower
    - py-region-grower@0.2.4
