spack:
  view: false
  concretization: separately
  modules:
    tcl:
      whitelist:
        - arm-forge
        - bison
        - blender
        - ccache
        - cli-tools
        - cmake
        - cuda
        - cudnn
        - darshan-runtime
        - darshan-util
        - doxygen
        - environment-modules
        - flex
        - ffmpeg
        - gdb
        - git
        - graphviz
        - hpctoolkit
        - hpcviewer
        - hpe-mpi
        - intel-mpi
        - ispc
        - julia
        - llvm
        - mvapich2
        - ninja
        - nvhpc
        - pgi
        - python
        - snakemake
        - stat
        - totalview
        - valgrind
        - virtualgl
  packages:
    all:
      providers:
        jpeg: [libjpeg-turbo]
        lapack: [intel-mkl]
    cairo:
      variants: +pdf+png
    graphviz:
      variants: +pangocairo+expat
    mvapich2:
      variants: fabrics=mrail process_managers=slurm file_systems=gpfs
    pgi:
      variants: +network+nvidia+mpi
  specs:
    - llvm@13.0.0 +cuda cuda_arch=70 +omp_tsan +python ^cuda@11.4.2
    - llvm@12.0.1 +cuda cuda_arch=70 +omp_tsan +python ^cuda@11.4.2
    - llvm@11.1.0 +cuda cuda_arch=70 +omp_tsan +python ^cuda@11.4.2
    - nvhpc@21.2 install_type=network
    - nvhpc@21.9
    - arm-forge
    - bison
    - blender
    - boost~mpi
    - bzip2
    - ccache
    - cgal
    - cli-tools
    - cmake
    - cuda@11.0.2
    - cuda@11.4.2
    - cudnn@8.0.3.33-11.0
    - darshan-runtime
    - darshan-util
    - doxygen
    - environment-modules@4.5.1
    - ffmpeg
    - flex
    - freetype
    - gdb~python
    - git
    - glew
    # Fails hard, too
    # - gmsh+metis~mpi+oce+openmp+shared@4.4.1
    - graphviz
    - hdf5~mpi@1.10.7
    - help2man
    - hpctoolkit@2020.03.01
    - hpcviewer
    - hpe-mpi@2.25.hmpt
    - intel-mkl
    # Leads to issues down the line, where it is preferred over hpe-mpi
    # #providers
    # - intel-mpi
    - ispc
    - julia
    - libxslt
    - libzmq+libsodium%intel
    - mvapich2@2.3.6
    - ncurses
    - ninja
    - openscenegraph  # doesn't like to be built in a spec with LLVM
    # Leads to issues down the line, where it is preferred over intel-mkl
    # #providers
    # - openblas
    - poppler
    - python
    - qhull@2015.2
    - qt@5.14.2
    - readline
    - snakemake
    - sqlite
    # Broken, broken, broken… :(
    # - stat
    # - symengine@0.3.0
    # - timemory
    - totalview
    - valgrind~mpi
    - virtualgl
    - vrpn
    - zlib
    # Viz stuff that complicates specs
    - ospray%intel target=x86_64
    - optix
