spack:
  view: false
  concretization: separately
  packages:
    trilinos:
      version: [xsdk-0.4.0-rc1]
  specs:
    - matrix:
        - [
            coreneuron,
            coreneuron+debug,
            hdf5+mpi,
            highfive+mpi,
            neuron,
            neuron+debug,
            ospray@1.7.3,
            ospray@1.8.5,
            python,
            py-h5py,
            py-h5py~mpi,
            py-mpi4py,
            py-numpy,
            py-pandas
          ]
        - ['%gcc', '%intel']
    - assimp
    - boost+python@1.70.0
    - boost+python@1.73.0
    - catch2
    - deflect
    - eigen
    - fmt
    - gmsh
    - hdf5~mpi
    - highfive~mpi
    - hypre+metis+mpi+oce+openmp+shared
    - libarchive
    - libxml2
    - metis+int64
    - morphio
    - morpho-kit
    - mvdtool+mpi
    - neuron+mpi~debug%intel
    - nlohmann-json +single_header
    - omega-h+trilinos@9.33.0.dev1
    - omega-h+gmsh+trilinos@9.33.0.dev1
    - openscenegraph build_type=Release
    - parmetis
    - petsc~int64+mpi
    - petsc+int64+mpi
    - pugixml
    - py-argcomplete
    - py-argparse
    - py-aspy-yaml
    - py-babel
    - py-beautifulsoup4
    - py-breathe
    - py-cached-property
    - py-cffi
    - py-cfgv
    - py-click
    - py-clustershell
    - py-cmake-format
    - py-configparser
    - py-contextlib2
    - py-coverage
    - py-cycler
    - py-cython
    - py-dask-mpi
    - py-dateutil
    - py-deap
    - py-decorator
    - py-docopt
    - py-exhale
    - py-flake8
    - py-funcsigs
    - py-future
    - py-hdfs
    - py-humanize
    - py-identify
    - py-importlib-metadata
    - py-importlib-resources
    - py-ipykernel
    - py-ipyparallel
    - py-ipywidgets
    - py-jinja2
    - py-jprops
    - py-lazy-property
    - py-line-profiler
    - py-linecache2
    - py-lxml
    - py-markdown
    - py-matplotlib
    - py-morphio
    - py-morpho-kit
    - py-munkres
    - py-mvdtool~mpi
    - py-neurom
    - py-nodeenv
    - py-pathlib2
    - py-pbr
    - py-pillow
    - py-pip
    - py-plotly
    - py-ply
    - py-pre-commit
    - py-progress
    - py-py4j
    - py-pyarrow+parquet@0.15.1
    - py-pylru
    - py-pyspark@3.0.0
    - py-pytest
    - py-pyyaml
    - py-regex
    - py-requests
    - py-scikit-learn
    - py-scipy
    - py-seaborn
    - py-setuptools
    - py-setuptools-scm
    - py-simplejson
    - py-six
    - py-sphinx
    - py-sphinx-rtd-theme
    - py-sympy
    - python-dev
    - py-toml
    - py-urllib3
    - py-virtualenv
    - py-virtualenv-clone
    - py-virtualenvwrapper
    - py-wheel
    - py-zipp
    - random123
    - range-v3
    - rockets
    - rocksdb~static
    - spark@3.0.0
    - superlu-dist@5.4.0
