# External libraries and packages

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - arrow+parquet~python@0.11.0
      - boost~mpi@1.68.0
      - bzip2@1.0.6
      - cuda@9.0.176
      - cuda@9.2.88
      - cudnn@7.3
      - freeimage@3.18.0
      - gmsh+oce~mpi@3.0.6
      - hdf5~mpi@1.10.4
      - highfive~mpi@2.0
      - intel-mkl@2018.1.163
      - jdk@1.8.0_191-b12
      - libjpeg@1.2.90
      - libjpeg-turbo@1.5.90
      - libxml2@2.9.8
      - libxslt@1.1.29
      - metis@5.1.0
      - ncurses@5.9
      - ninja@1.8.2
      - openblas@0.3.3
      - optix
      - python@2.7.15
      - python@3.6.5
      - qhull@2015.2
      - qt@5.11.2
      - readline@7.0
      - spark@2.4.0+hadoop
      - sqlite@3.23.1
      - symengine@0.3.0
      - zeromq@4.2.5
      - zlib@1.2.11
