# Packages and libraries require MPI

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - hdf5+mpi@1.10.5
      - highfive+mpi
      - ospray@1.7.3
      - ospray@1.8.5
      - parmetis@4.0.3
      - mvdtool+mpi

  gnu-stable-python-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - py-mpi4py

  gnu-stable-parallel-lapack:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - lapack
    specs:
      - hypre@2.14.0
      - omega-h+gmsh+trilinos@9.31.2.dev2
      - superlu-dist@5.4.0
      - trilinos@xsdk-0.4.0-rc1
      - omega-h+trilinos@9.29.0

  gnu-stable-parallel-lapack-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - lapack
      - mpi
      - python
    specs:
      - petsc+int64+mpi@3.12.1

  intel-stable-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - hdf5+mpi@1.10.5
      - highfive+mpi@2.1.1
      - ospray@1.7.3
      - ospray@1.8.5

  intel-stable-parallel-python:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - neuron
      - neuron+debug
      - py-h5py
      - py-mpi4py
