# Packages and libraries require MPI

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - hdf5+mpi@1.10.4
      - highfive+mpi@2.0
      - ospray@1.7.3
      - ospray@1.8.5
      - parmetis@4.0.3
      - mvdtool+mpi~python

  gnu-stable-python-parallel:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - py-mpi4py@3.0.0

  gnu-stable-parallel-lapack:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - mpi
      - lapack
    specs:
      - hypre@2.14.0
      - omega-h+trilinos@9.29.0
      - superlu-dist@5.4.0
      - trilinos@xsdk-0.4.0-rc1

  gnu-stable-parallel-lapack-python:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - lapack
      - mpi
      - python
    specs:
      - petsc+int64+mpi@3.10.2

  intel-stable-parallel:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
    specs:
      - hdf5+mpi@1.10.4
      - highfive+mpi@2.0
      - ospray@1.7.3
      - ospray@1.8.5

  intel-stable-parallel-python:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
      - mpi
      - python
    specs:
      - neuron@7.6.8
      - neuron+debug@7.6.8
      - 'py-h5py@2.9.0 ^py-numpy~blas~lapack'
      - py-mpi4py@3.0.0
