# Serial libraries and packages

axis:
  - architecture
  - compiler
  - mpi
  - lapack
  - python

combinations: !include packages/toolchains.yaml

packages:

  gnu-stable-serial-python:
    target_matrix:
      - gnu-stable
      - gnu-stable-py2
    requires:
      - architecture
      - compiler
      - python
    specs:
      - arrow+parquet+python@0.11.0
      - neuron~mpi@7.6.8

  gnu-stable-serial-python3:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
      - python
    specs:
      - boost+python
      - tensorflow@1.12.0+cuda

  gnu-intel-stable-serial:
    target_matrix:
      - gnu-stable
      - intel-stable
    requires:
      - architecture
      - compiler
    specs:
      - python@2.7.15
      - python@3.6.5

  gnu-stable-serial:
    target_matrix:
      - gnu-stable
    requires:
      - architecture
      - compiler
    specs:
      - assimp
      - boost
      - deflect
      - eigen
      - fmt
      - gmsh
      - hdf5~mpi
      - highfive~mpi
      - libarchive
      - morphio
      - pugixml
      - range-v3
      - rockets
      - rocksdb~static

  intel-stable-serial:
    target_matrix:
      - intel-stable
    requires:
      - architecture
      - compiler
    specs:
      - embree
