modules:

  enable::
    - tcl

  prefix_inspections::
    bin:
      - PATH
    bin64:
      - PATH
    share/man:
      - MANPATH
    man:
      - MANPATH
    lib:
      - LD_LIBRARY_PATH
    lib64:
      - LD_LIBRARY_PATH
    lib/pkgconfig:
      - PKG_CONFIG_PATH
    lib64/pkgconfig:
      - PKG_CONFIG_PATH
    '':
      - CMAKE_PREFIX_PATH

  tcl:
    verbose: True
    hash_length: 0
    whitelist:
      - brainbuilder
      - functionalizer
      - 'neurodamus%intel'
      #- 'neuron+mpi%intel'
      - neurodamus-hippocampus
      - neurodamus-neocortex
      - neurodamus-thalamus
      - parquet-converters
      - placement-algorithm
      - py-bluepymm
      - py-bluepyopt
      - py-efel
      - py-pytouchreader
      - spykfunc
      - 'synapsetool%gcc'
      - steps
      - touchdetector
    blacklist:
      - '%gcc'
      - '%intel'
      - '%clang'
      - '%pgi'
    naming_scheme: '${PACKAGE}/${VERSION}'
    all:
      autoload: 'all'
      suffixes:
        '^python@:2.99': '/python2'
        '^python@3:': '/python3'
        '^coreneuron+knl': knl
        '+mpi': '/parallel'
      environment:
        set:
          '${PACKAGE}_ROOT': '${PREFIX}'
